package org.launchcode;

import java.util.Comparator;


// BONUS MISSION #1: Sort Flavor objects by the NUMBER of Allergens from HIGHEST to LOWEST
public class FavorAllergensComparator implements Comparator<Flavor> {

    // Generated by selecting "Implement methods" >> chooose "compare(o1:T, o2:T):int"
    @Override
    public int compare(Flavor flavor1, Flavor flavor2) {

        if (flavor1.getAllergens().size() - flavor2.getAllergens().size() > 0) {
            // Returns NEGATIVE if '# of Allergens in flavor1' < '# of Allergens in flavor2'
            return -1;

        } else if (flavor1.getAllergens().size() - flavor2.getAllergens().size() < 0) {
            // Returns POSITIVE if '# of Allergens in flavor1' > '# of Allergens in flavor2'
            return 1;

        } else {
            // Return "0" indicates No Sorting if '# of Allergens in flavor1' == '# of Allergens in flavor2'
            return 0;
        }
    }
}
